function start_cpu()
  print("cpu started")
end

local optable = {
  ["BRK"] = function() end, --00
  ["ORA"] = function() end, --01, 05, 09, 0D, 11, 15, 19, 1D
  ["KIL"] = function() end, --02, 12, 22, 32, 42, 52, 62, 72, 92, B2, D2, F2
  ["SLO"] = function() end, --03, 07, 0F, 13, 17, 1B, 1F
  ["NOP"] = function() end, --04, 0C, 14, 1A, 1C, 34, 3A, 3C, 44, 54, 5A, 5C, 64, 74, 7A, 7C, 80, 82, 89, C2, D4, DA, DC, E2, EA, F4, FA, FC
  ["ASL"] = function() end, --06, 0A, 0E, 16, 1E
  ["PHP"] = function() end, --08
  ["ANC"] = function() end, --0B, 2B
  ["BPL"] = function() end, --10
  ["CLC"] = function() end, --18
  ["JSR"] = function() end, --20
  ["AND"] = function() end, --21, 25, 29, 2D, 31, 35, 39, 3D
  ["RLA"] = function() end, --23, 27, 2F, 33, 37, 3B, 3F
  ["BIT"] = function() end, --24, 2C
  ["ROL"] = function() end, --26, 2A, 2E, 36, 3E
  ["PLP"] = function() end, --28
  ["BMI"] = function() end, --30
  ["SEC"] = function() end, --38
  ["RTI"] = function() end, --40
  ["EOR"] = function() end, --41, 45, 49, 4D, 51, 55, 59, 5D
  ["SRE"] = function() end, --43, 47, 4F, 53, 57, 5B, 5F
  ["LSR"] = function() end, --46, 4A, 4E, 56, 5E
  ["PHA"] = function() end, --48
  ["ALR"] = function() end, --4B
  ["JMP"] = function() end, --4C, 6C
  ["BVC"] = function() end, --50
  ["CLI"] = function() end, --58
  ["RTS"] = function() end, --60
  ["ADC"] = function() end, --61, 65, 69, 6D, 71, 75, 79, 7D
  ["RRA"] = function() end, --63, 67, 6F, 73, 77, 7B, 7F
  ["ROR"] = function() end, --66, 6A, 6E, 76, 7E
  ["PLA"] = function() end, --68
  ["ARR"] = function() end, --6B
  ["BVS"] = function() end, --70
  ["SEI"] = function() end, --78
  ["STA"] = function() end, --81, 85, 8D, 91, 95, 99, 9D
  ["SAX"] = function() end, --8B, 8F, 97, 9F
  ["STY"] = function() end, --8C, 94, 9C
  ["STX"] = function() end, --8E, 96, 9E
  ["DEY"] = function() end, --88
  ["TXA"] = function() end, --8A
  ["XAA"] = function() end, --8B
  ["BCC"] = function() end, --90
  ["AHX"] = function() end, --93, 9F
  ["TYA"] = function() end, --98
  ["TXS"] = function() end, --9A
  ["TAS"] = function() end, --9B
  ["SHY"] = function() end, --9C
  ["SHX"] = function() end, --9E
  ["LDY"] = function() end, --A0, A4, AC, B4, BB
  ["LDA"] = function() end, --A1, A5, A9, AD, B1, B5, B9, BD
  ["LDX"] = function() end, --A2, A6, AE, B6, BE
  ["LAX"] = function() end, --A3, A7, AB, AF, B3, B7, BF
  ["TAY"] = function() end, --A8
  ["TAX"] = function() end, --AA
  ["BCS"] = function() end, --B0
  ["CLV"] = function() end, --B8
  ["TSX"] = function() end, --BA
  ["LAS"] = function() end, --BB
  ["CPY"] = function() end, --C0, C4, CC
  ["CMP"] = function() end, --C1, C5, C9, CD, D1, D5, D9, DD
  ["DCP"] = function() end, --C3, C7, CF, D3, D7, DB, DF
  ["DEC"] = function() end, --C6, CE, D6, DE
  ["INY"] = function() end, --C8
  ["DEX"] = function() end, --CA
  ["AXS"] = function() end, --CB
  ["BNE"] = function() end, --D0
  ["CLD"] = function() end, --D8
  ["CPX"] = function() end, --E0, E4, EC
  ["SBC"] = function() end, --E1, E5, E9, EB, ED, F1, F5, F9, FD
  ["ISC"] = function() end, --E3, E7, EF, F3, F7, FB, FF
  ["INC"] = function() end, --E6, EE, F6, FE
  ["INX"] = function() end, --E8
  ["BEQ"] = function() end, --F0
  ["SED"] = function() end, --F8
}